### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by ramya-rao-a** [felixfbecker/vscode-php-debug#149]
_From @Yagneshdxt on March 12, 2017 11:26_

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|csharp|ms-vscode|1.7.0|
|mono-debug|ms-vscode|0.15.3|
|laravel-blade|onecentlin|1.8.1|;

---

Steps to Reproduce:

1. click on start debugging button on debugging tab. (I am debugging php file wiht felixfbecker.php-debug extension)
2. Debugger shows error Debug adapter process has terminated unexpectedly 
on my developer tool it shows error in workbench.main.js:103

My debugging was working fine before vscode update after vscode update it started showing this error.

_Copied from original issue: Microsoft/vscode#22476_

**Comment by ramya-rao-a** [comment]
@Yagneshdxt Is this happening consistently? Can you share the error you see in the debug console and developer console if any?

cc @felixfbecker

**Comment by ramya-rao-a** [comment]
_From @felixfbecker on March 12, 2017 18:32_

Feel free to move the issue, I need to see some stack trace from eg dev tools

**Comment by neild3r** [comment]
I'm having the same issue but I don't have it in the insider version. I don't get anything useful from dev tools but I could look a little deeper and see what I can find out

**Comment by neild3r** [comment]
OK after a deeper look it seems that it's my theme that's causing the issue @ramya-rao-a  could you switch to the default editor theme and see if that at least temporarily resolves the issue?

**Comment by neild3r** [comment]
Actually ignore me, it probably won't be the same issue I had something else messing with mine

**Comment by levani** [comment]
I'm having the same issue on vs code 1.10.2

**Comment by Yagneshdxt** [comment]
![vsdebugerror](https://cloud.githubusercontent.com/assets/11188564/24393140/909401ce-13b4-11e7-9653-eda87f7b68f4.png)

Hi @ramya-rao-a  please find attached screen shot

If you can help me with steps to get more details about error. 
I will happy to help you with more detail error log.

**Comment by felixfbecker** [comment]
What is your launch.json?
EACCESS 81 indicates you use port 81 but don't run with root permissions to bind on that port.

**Comment by Yagneshdxt** [comment]
{
    "version": "0.2.0",
    "configurations": [
    
            {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 81
        }
    ]
}

**Comment by Yagneshdxt** [comment]
@felixfbecker 

My debugger was working fine before I updated VSCode. I never faced any issue.  I have not changed any access or any of the setting but suddenly after update it stopped working.

Please help me further.  I am not able to find any access issue. I ran VSCode with administrator right but I got the same error. 

Please find below my port setting.

; Local Variables:
; tab-width: 4
zend_extension = "D:\Yagnesh\php\ext\php_xdebug-2.5.1-7.1-vc14-nts.dll"
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_port = 9000
; End:

**Comment by felixfbecker** [comment]
Well maybe VS Code broke running as admin. But the log in your screenshot clearly shows `listen EACCESS 0.0.0.0:80`. Which corresponds to your port setting in launch.json - change the port to 9000

**Comment by levani** [comment]
I had a different case lately that was not related to port number... Not sure if this is the cause of the problem but this extension doesn't work reliably when there are many concurrent requests being processed. When there are 4-5+ items in call stack and I hit the restart icon (green round arrow) it always crashes with the above message.

I managed to reproduce this consistently with a sample project attached to this comment. In this project `index.php` file is sending multiple ajax requests at the same time. In `file2.php` - `file7.php` there is `sleep(30)` to keep the process in call stack for a while. Try opening `file8.php` and create new breakpoint somewhere in the top. Than reload the browser where `index.php` is opened and once the breakpoint is hit try to restart the debug process (that green arrow or ctrl + shift + f5).
![rec](https://cloud.githubusercontent.com/assets/184472/24403298/4be4331e-13cd-11e7-8e15-c5176950d74a.gif)

https://drive.google.com/file/d/0B7Ls870jI1CLZWFkazdySHdBTFE/view?usp=sharing

**Comment by felixfbecker** [comment]
@levani that is a different issue, please don't hijack the thread. XDebug's protocol is serial, so if your script is in a running state (not stopped on a breakpoint or ended) because of a `sleep` or whatever, we cannot send it the request to terminate, so we have to wait until it returns a stopped response. If you impatiently spam the restart button, then VS Code will just spawn a new debug adapter despite the old one not properly terminated which results in an EADDRINUSE error because the port is still blocked by the other process. This is a different error than EACCESS.

**Comment by bakeiro** [comment]
same for me, after update i can not debug with xDebugger

Version : 1.18.1
So : Win 10

**Comment by dodongphure** [comment]
Got this problem too like @bakeiro and I used php_xdebug-2.5.5-5.6-vc11

**Comment by DeanNonatomic** [comment]
After the recent VSCode update I get the above error each time I attempt to debug. This worked fine before the update. This is my launch.json:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for XDebug",
			"type": "php",
			"request": "launch",
			"port": 9000,
			"pathMappings": {
				"/mnt/[path to my remote working directory]": "${workspaceRoot}/site"
			}
		}
	]
}
```

**Comment by rajeev123045** [comment]
@bakeiro same is happening with on my system after update.

**Comment by KenMurphy** [comment]
Same issue here. Left work yesterday with it working fine and came in today to it being broken. I haven't changed anything.

**Comment by CesarGA** [comment]
I started having the same issue a few hours ago.

VSCode 1.18.1
Windows 10

**Comment by ekernd** [comment]
Same issue started for me :  Debug adapter process has terminated unexpectedly

VSCode 1.18.1
Windows 10

**Comment by thisboyiscrazy** [comment]
Same problem VSCode 1.18.1
Ubuntu linux 17.10

```
[14660:1121/123011.834411:INFO:CONSOLE(5)] "[uncaught exception]: Error: read ECONNRESET", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[14660:1121/123011.834460:INFO:CONSOLE(5)] "Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[14660:1121/123011.834476:INFO:CONSOLE(163)] "Uncaught Error: read ECONNRESET", source: events.js (163)
[14660:1121/123011.835207:INFO:CONSOLE(9)] "Debug adapter process has terminated unexpectedly", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (9)
[14660:1121/123012.921884:INFO:CONSOLE(5)] "[uncaught exception]: Error: read ECONNRESET", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[14660:1121/123012.921920:INFO:CONSOLE(5)] "Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at Pipe.onread (net.js:581:26)", source: file:///usr/share/code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[14660:1121/123012.921937:INFO:CONSOLE(163)] "Uncaught Error: read ECONNRESET", source: events.js (163)
[14660:1121/123012.922326:INFO:CONSOLE(9)] "Debug adapter process has terminated unexpectedly", source: file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js (9)
```

**Comment by DeanNonatomic** [comment]
https://github.com/felixfbecker/vscode-php-debug/issues/203

**Comment by hindleg** [comment]
I had same problem after updating to VSCode 1.18.1 on Windows 10.

I tried a reboot and restart VSCode. When it opened up it opened the User Settings file. I have a custom block the php 5.4 I use. This had some errors marked. I'm not sure if this was a result of the VSCode update or not. I fixed the errors. Restarted VSCode -> Still not working. 

Then I noticed in my list of extensions, the PHP Debug extension had an update button. I don't know what version it was, but it's now 1.12.1 and it's back working again.

**Comment by bagermen** [comment]
Confirm the bug!!!

Ubuntu 16.04 LTS

Version 1.17.2
and insider version (1.19)

I have the same problem after update.

Also DEB packages were not updated properly (installation script hanged up)

This problem is serious.. do something with it already, please

**Comment by rckjairath** [comment]
I am also facing the same issue whenever I tries to step into the debugger stops with error :
debug adapter process has terminated unexpectedly
Here is my launch.json

{
    "version": "0.2.0",
    "configurations": [

        
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

**Comment by marcpre** [comment]
Can confirm the error. 
Windows 8
PHP 7.1.8

![image](https://user-images.githubusercontent.com/30902582/33776187-e0ead76a-dc40-11e7-92da-f125d1212b22.png)


Below my `launch.json` file

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}
```
Any fix for this error?

**Comment by neerajsinghsonu** [comment]
Hi All,

I had same issue while I was start using VSCode. Well i took 3 hours to figure out what is exactly issue, I just stared with some step by step debugging like what port being used and what are the other settings.

Finally I was lucky and got the solutions :) So I created a page to share with everyone. You can check what is my findings and what you should need to setup to get Xdebug work with VSCode.

Link: [How-to-setup-PHP-Debugging-xdebug-with-VSCode-Visual-Studio-Code](https://github.com/neerajsinghsonu/How-to-setup-PHP-Debugging-xdebug-with-VSCode-Visual-Studio-Code-)

Hope my experience would be helpful for someone.  Cheers!!!

**Comment by arby50** [comment]
Had the same issue this morning, worked yesterday night, updated VSCode to 1.22 and got the error above.  Changed php.ini and launch.json to use port 9002, confirmed via netstat that nothing was using either 9000 or 9002, went back to VSCode 1.21, nothing.  Had to disable auto-update and go back to PHP Debug 1.11 and now it works.

**Comment by loppp** [comment]
Same here. Updated VSCode to 1.22.2 and got the error.
