### ISSUE TITLE
adapter terminated, cannot find module phpdebug.js

### ISSUE THREAD

**Issue by dynamicapps** [felixfbecker/vscode-php-debug#319]
Getting this error when I do "Listen for XDebug".  Windows 10.  vscode 1.29.1.  php 7.1.11.
Ideas?

module.js:545
    throw err;
    ^
Error: Cannot find module 'c:/Users/John/.vscode/extensions/felixfbecker.php-debug-1.12.6/out/phpDebug.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at [eval]:1:41
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Object.<anonymous> ([eval]-wrapper:8:3)
    at Module._compile (module.js:642:30)

**Comment by dynamicapps** [comment]
As those more knowledgeable probably already know, this was a problem with installation.  What I didn't realize was that I had to delete the folder for the extension rather than just uninstall and reinstall.
