### ISSUE TITLE
VSCodium: It won't even bind the listening port while vdebug works perfectly fine

### ISSUE THREAD

**Issue by jm33-m0** [felixfbecker/vscode-php-debug#414]
Choose "listen for xdebug", the debugger does nothing, it won't listen for anything, the port 9000 is still free!

I tried with vdebug in vim, which worked totally fine

No, port 9000 is not occupied when testing this plugin

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}
```

**Comment by Androphin** [comment]
@jm33-m0 What shows your console output (Help > Toggle Developer Tools) if you start the debugger?

My debug session wont start either. If I'm trying to start listening, I get the following error in console:

> ERR timeout after 1000 ms: Error: timeout after 1000 ms /opt/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:1670
    at t.RawDebugSession.handleErrorResponse (file:///opt/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:3160:190)
    at file:///opt/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:3159:451
    at async t.RawDebugSession.shutdown (file:///opt/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:3157:536)

**Comment by ekkis** [comment]
doesn't seem this product works at all, nor that there's any support for it.  when I start the debugger it states it's listening but it doesn't hit any of my breakpoints

**Comment by jm33-m0** [comment]
@ekkis it's not listening on any port, it just silently quits, I couldn't see a single error
There's no documentation either
I guess the author think it automatically works

@Androphin I'm using vscodium too, it might be something with vscodium

**Comment by ekkis** [comment]
like everything else in the open source world, hopelessly broken

**Comment by jm33-m0** [comment]
@ekkis Really annoying me, guess I will keep using vim

**Comment by ekkis** [comment]
I installed PhpStorm but cannot make it work either

**Comment by playmono** [comment]
> @ekkis it's not listening on any port, it just silently quits, I couldn't see a single error
> There's no documentation either
> I guess the author think it automatically works
> 
> @Androphin I'm using vscodium too, it might be something with vscodium

100% this

**Comment by playmono** [comment]
Confirmed It doesn't work on Codium. Spent 4 hours trying to make it work.

Works fine in Vscode.

**Comment by ekkis** [comment]
> Works fine in Vscode.

I'd be happy if I could make it work in VSCode.  I only installed PhpStorm because VSCode didn't work

**Comment by Androphin** [comment]
> Confirmed It doesn't work on Codium. Spent 4 hours trying to make it work.
> 
> Works fine in Vscode.

Why is that? I thought Codium has the same codebase just without telemetry activated.

**Comment by jeremyswright** [comment]
I managed to get dbgpClient working, but php-debug wouldn't stop at a breakpoint or give out any real reason why. Nothing in the debug console, just this in the log file. Top section from php-debug, lower from dbgpClient.

```
[23158] Log opened at 2020-07-28 13:32:01
[23158] I: Checking remote connect back address.
[23158] I: Checking header 'HTTP_X_FORWARDED_FOR'.
[23158] I: Checking header 'REMOTE_ADDR'.
[23158] W: Remote address not found, connecting to configured address/port: localhost:9000. :-|
[23158] W: Creating socket for 'localhost:9000', poll success, but error: Operation now in progress (29).
[23158] E: Could not connect to client. :-(
[23158] Log closed at 2020-07-28 13:32:01

[23228] Log opened at 2020-07-28 13:33:01
[23228] I: Checking remote connect back address.
[23228] I: Checking header 'HTTP_X_FORWARDED_FOR'.
[23228] I: Checking header 'REMOTE_ADDR'.
[23228] W: Remote address not found, connecting to configured address/port: localhost:9000. :-|
[23228] I: Connected to client. :-)
[23228] -> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" fileuri="file:///var/www/aceto/artisan" language="PHP" xdebug:language_version="7.2.24-0ubuntu0.18.04.6" protocol_version="1.0" appid="23228"><engine version="2.9.6"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[https://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2020 by Derick Rethans]]></copyright></init>

```
I'm not sure it's worth the effort of compiling all the details and issuing a bug report if the software is no longer maintained....

**Comment by brunob** [comment]
FTR, since the bug is in codium https://github.com/VSCodium/vscodium/issues/466 this issue could be closed. Bonus, it will prevent @felixfbecker from sarcastic comments :p

**Comment by brunob** [comment]
As said here https://github.com/VSCodium/vscodium/issues/466#issuecomment-690931332 codium 1.49.0 seems to fix this bug.

**Comment by jm33-m0** [comment]
@brunob Okay, I am closing this one
